# Generated by Django 5.1.3 on 2024-11-24 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pozisyon', models.CharField(default='Personel', max_length=100)),
                ('personel_id', models.CharField(max_length=100)),
                ('kalan_izin', models.PositiveIntegerField(default=15)),
                ('aylik_calisma_saati', models.FloatField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personel2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IzinTalebi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslangic_tarihi', models.DateField()),
                ('bitis_tarihi', models.DateField()),
                ('onaylandi', models.BooleanField(default=False)),
                ('reddedildi', models.BooleanField(default=False)),
                ('personel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='izin_talepleri', to='personel.personel')),
            ],
        ),
        migrations.CreateModel(
            name='GirisCikis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giris_saati', models.DateTimeField()),
                ('cikis_saati', models.DateTimeField(blank=True, null=True)),
                ('tarih', models.DateField(auto_now_add=True)),
                ('personel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giris_cikislar', to='personel.personel')),
            ],
        ),
    ]
